#!/bin/bash

for file in $(find ../cpp/src/main -name "*.h" -a ! -name "*macros.h" -a ! -name "*SortPair*")
#for file in ../cpp/src/main/data_generators/TimeframeDataGenerator.h ../cpp/src/main/models/Model.h ../cpp/src/main/general_interfaces/Initializable.h
do
  standard_guard=$(egrep "^ *class [^;]*$" $file | grep -v "enum" | head -1 | sed -r "s/^[[:space:]]*class[[:space:]]+([a-zA-Z]+)([^a-zA-Z].*)?$/\1_h/" | sed -r "s/([A-Z])/_\1/g" | sed -r "s/^_//" | tr [a-z] [A-Z])
  standard_guards="$standard_guards$standard_guard\n"
  standard_header=$(echo -e "#ifndef $standard_guard\n#define $standard_guard\n")
  actual_header=$(head -2 $file)
  if [ x"$standard_header" != x"$actual_header" ]
  then
    failed_files="$failed_files$file\n"
    echo error: $file "("$actual_header")" "->" $standard_guard
  fi
  standard_footer="#endif /* $standard_guard */"
  actual_footer=$(tail -1 $file)
  if [ x"$standard_footer" != x"$actual_footer" ]
  then
    footer_failed_files="$footer_failed_files$file\n"
  fi
  #overwriting
  head -n-1 $file | tail -n+3 > tmp
  echo -e "$standard_header" > ${file}
  cat tmp >> ${file}
  echo -e "$standard_footer" >> ${file}
done
rm tmp

echo Failed files:
echo -e $failed_files
echo Footer failed files:
echo -e $footer_failed_files
echo Duplicated guards:
echo -e "$standard_guards" | sort | uniq -d
