#!/bin/bash

script_dir=$(dirname $0)

echo -n "Number of autoconverted sip files: "
grep -l "//SIP_AUTOCONVERT" $(ls $(find $script_dir/../../sip/src/ -name "*.sip" | sed "s|sip/src|cpp/src/main|" | sed "s/[.]sip/.h/" ) 2>/dev/null ) | wc -l

echo -n "Number of non autoconverted sip files: "
grep -L "//SIP_AUTOCONVERT" $(ls $(find $script_dir/../../sip/src/ -name "*.sip" | sed "s|sip/src|cpp/src/main|" | sed "s/[.]sip/.h/" ) 2>/dev/null ) | wc -l
